[tool.poetry]
name = "redbox"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
markdown = "^3.6"
python-docx = "^1.1.0"
unstructured = "^0.13.2"
langchain = "^0.1.16"
pydantic = "^2.7.0"
elasticsearch = "^8.13.0"
elastic-transport = "^8.13.0"
sentence-transformers = "^2.7.0"
tiktoken = "^0.6.0"
pydantic-settings = "^2.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
boto3 = "^1.34.87"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
